version: '2.1'

services:
  app:
    image: maxca789/apache-php72
    container_name: book-can-says
    restart: always
    ports:
      - "8900:80"
    volumes:
      - .:/var/www/html
    mem_limit: 2048m
    networks:
      - bookcansays-network
    cap_add:
      - SYS_PTRACE
networks:
  bookcansays-network:
    external: true