version: '2.1'

services:
  app:
    image: maxca789/apache-php72
    container_name: book-can-says
    restart: always
    ports:
      - "8821:80"
    volumes:
      - .:/var/www/html
    mem_limit: 2048m
    networks:
      - bb-intranet-network
    cap_add:
      - SYS_PTRACE
networks:

  bb-intranet-network:
    external: true




